modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="mobheads"
version="${file.jarVersion}"
displayName="Mob Heads"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
credits="VanillaTweaks team for all the mob heads! https://vanillatweaks.net/"
authors="Insane96"
description='''
This simple mod makes all mobs able to drop heads. Datapack driven!
'''
[[dependencies.mobheads]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobheads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobheads]]
    modId = "insanelib"
    mandatory = true
    versionRange = "[1.1.0,)"
    ordering = "NONE"
    side = "BOTH"